# Generated by Django 5.0.4 on 2024-04-19 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MonitorTK', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bdproductions',
            name='decision_text',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
